### ISSUE TITLE
Fix alpha and beta flatpak repos

### ISSUE THREAD

**Issue by trickypr** [focus-browser/browser#121]

**Comment by x80486** [comment]
Do you plan on publishing `Pulse` to `Flathub` at some point?

**Comment by trickypr** [comment]
Yes, I do. However flathub does not accept alpha or beta apps, they want your stable version. Hence, this is tracking our own repo for alpha and beta builds.

**Comment by x80486** [comment]
I think you might be able to get a compromise and publish `Pulse` because this is your mainstream channel for now.

If that doesn't work (although I doubt it), you can definitely publish to the [beta channel](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/tree/beta). In this way you are going to be able to receive feedback more quickly because more people are going to be able to try `Pulse`.

**Comment by trickypr** [comment]
I wasn't aware that flatpak had a beta channel that I would be able to publish to. I will look into it in the future, but until we stop adding features and start focusing more on polish, I would want to avoid getting too much attention
