### ISSUE TITLE
Ranmaru22's UserChrome does not play nice with the sidebar

### ISSUE THREAD

**Issue by TooSpooky** [focus-browser/browser#134]
Hello,

One thing I've grown to love is having side tabs, currently my favorite implementation on Firefox is https://github.com/ranmaru22/firefox-vertical-tabs using Tab Center Reborn, sadly it doesn't fit properly when trying to use it on Pulse and I'm unfamiliar with CSS. 

I think it would make a fantastic addition to the browser and make me consider switching. 

Thanks for your time and take care!

**Comment by PressJump** [comment]
Currently the pulse sidebar is setup in a way like bookmarks where you can utilize the sidebar to open websites on your side-view. This may be the issue with styling as this is something we have added to Firefox utilizing the base sidebar API. Can you provide pictures on the issue you are having with the extension?

**Comment by TooSpooky** [comment]
Hey,

I should have rephrased that. Tab center reborn works fine and actually blends in well with side bar in my opinion. Just unsurprisingly the CSS that turns tab center reborn into more of an edge style of tabs, I.E. no top tabs, tabs hide to favicon until you hover over the sidetab bar, etc doesn't fit properly and breaks.

Examples:

Without CSS

<img width="460" alt="pulse-browser_8K7nUAr7Gy" src="https://user-images.githubusercontent.com/21211292/200102562-d6849b79-af00-468c-93df-d9608c0907ef.png">

With CSS 

![pulse-browser_jho155R7gm](https://user-images.githubusercontent.com/21211292/200102568-d2c1b41f-7b64-4917-8f25-a0a432323d6d.jpg)

Sadly i'm unfamiliar with CSS and I'm sure it could be fixed with an edit. Having a similar function build into the browser could be a nice feature in the future I personally believe.

Thanks for the quick reply!

**Comment by PressJump** [comment]
Ah I see. I am not too sure if we will have sidebar-tabs as a future addition but I will add it to the list of things to experiment with. Coming to the CSS, unfortunately that will be more difficult to work with due to the custom sidebar we have in pulse. I will have a look around the styling they provide and will return to you with results after testing it on the browser and modifying it.

**Comment by TooSpooky** [comment]
Sweet, sounds good I know it's not everyone's cup of tea. Thanks a ton man, I'll happily wait for and see what results you get.  Appreciate it!

**Comment by PressJump** [comment]
Hey @TooSpooky update. Unfortunately firebox-vertical-tabs extension utilizes the same firefox API as we utilize which makes it so that you are not able to use the pulse sidebar while having the sidebar of the extension. In the case lets say you did not use the sidebar at all to open anything else, then you would have two sidebars on the browser which takes more than needed amount of space. Due to this, I recommend not having the sidebar that the extension provides at all but utilizing the extension on the pulse sidebar.

To hide the tabs above so you can use the sidebar primarily for your tabs I have removed the sidebar styling from line 240 to 334 included in their provided UserChrome file.

Removed code for formatting purposes.

UserChrome from firefox-vertical-tabs available at https://github.com/ranmaru22/firefox-vertical-tabs/blob/main/userChrome.css under GPL-3.0 license found at https://github.com/ranmaru22/firefox-vertical-tabs/blob/main/LICENSE

Preview:
![image](https://user-images.githubusercontent.com/40802367/200110864-1f9a7f9f-d670-4296-8e3c-eba3f27e0212.png)

**Comment by TooSpooky** [comment]
Hey,

That's rather unfortunate but thanks a ton for checking it out and messing around with it. Definitely gonna try it out like that, blends quite well.

**Comment by TooSpooky** [comment]
Hey,

It seems to work fine on my end by doing that, thanks again! Especially for diving in and testing stuff haha. Would be better if it could be shrunk to just show the tab preview image but this allows me to definitely more happily check out Pulse and it's updates.

Looking forward to watching Pulses progress!

**Comment by PressJump** [comment]
Hey thanks alot for the kind words. Doing stuff like this makes it possible for future users to use the extension you were using for sidebar tabs. What do you also mean by shrunk to just show the tab preview. While we are here, we may as well just fix if there is any issues right :). I will keep the issue open for this case.

Hope you enjoy your experience with pulse!

**Comment by TooSpooky** [comment]
Hey no problem. Great to hear. I mean only show about this much, granted i'd assume that's probably hard coded by the extension itself haha. I will make sure to enjoy it!

<img width="433" alt="ndCSdaO3PK" src="https://user-images.githubusercontent.com/21211292/200236073-e5d52217-b4bd-45ca-b4d9-e0481cc849bb.png">

**Comment by trickypr** [comment]
I am changing this to a tracking issue for this specific bug because that seems to be more relevant to the content. Technical / design discussions for our own implementation will happen in #137.

**Comment by PressJump** [comment]
For anyone visiting this issue related to utilizing Tab Center Reborn, we have recently implemented our version of vertical tabs with Pulse on issue #137 like Tricky has said. It is available to be enabled in the browser settings. Closing this issue for now.
