### ISSUE TITLE
uBlock on Sidebar

### ISSUE THREAD

**Issue by PressJump** [focus-browser/browser#157]
Currently uBlock does not affect the sidebar.

Made for tracking purposes to be done after #146.

**Comment by PressJump** [comment]
I believe this will need a great amount of investigation and modification, so pushing back until PR #159 and PR #165

**Comment by PressJump** [comment]
Investigating the issue for adblock application on sidebar browser.

**Comment by PressJump** [comment]
Unfortunately I am not too sure if this is possible in the time frame we have. I have tried many ways of enabling the effects of uBlock on the sidebar views but the documentation being older than me does not help. I am tagging this as help needed.

**Comment by garry-ut99** [comment]
In XUL was possible ==> In WebExtensions not anymore : https://github.com/gorhill/uBlock/issues/2995 ==> In MV3 possible again, but declarativeNetRequest API is not yet available in the current implementation of MV3 in Firefox:
https://github.com/uBlockOrigin/uBlock-issues/issues/2524#issuecomment-1453826861 + 
https://github.com/uBlockOrigin/uBlock-issues/issues/2524#issuecomment-1454840636 + 
https://github.com/uBlockOrigin/uBlock-issues/issues/2524#issuecomment-1454870518

**Comment by Ryosuke-Asano** [comment]
Hi, @PressJump 

Floorp has same problem. but, I could understand the cause.

Well, many addons need "tab" permission. However, it turns out that this doesn't work for normal browser elements or panels inside sidebars.

The solution is to embed "chrome://browser/content/browser.xhtml" but unfortunately it's almost certain that you can't manipulate this embedded site with JS.

The normal site view works because it is associated with tabs. Unfortunately, nothing displayed in the sidebar is tied to tabs, and Bugzilla considers "tab" to be the most complicated and difficult part of Mozilla's source code. Giving up is wise.

**Comment by PressJump** [comment]
> Hi, @PressJump
> 
> Floorp has same problem. but, I could understand the cause.
> 
> Well, many addons need "tab" permission. However, it turns out that this doesn't work for normal browser elements or panels inside sidebars.
> 
> The solution is to embed "chrome://browser/content/browser.xhtml" but unfortunately it's almost certain that you can't manipulate this embedded site with JS.
> 
> The normal site view works because it is associated with tabs. Unfortunately, nothing displayed in the sidebar is tied to tabs, and Bugzilla considers "tab" to be the most complicated and difficult part of Mozilla's source code. Giving up is wise.

I see. I understand that routing the js of ublock would also be a problem. I will keep the issue open for any future changes but this is a large roadblock. Thank you for your help.
