### ISSUE TITLE
Sidebar visible in Fullscreen

### ISSUE THREAD

**Issue by PressJump** [focus-browser/browser#90]
The sidebar is visible in fullscreen services where it is not supposed to be visible. 
![image](https://user-images.githubusercontent.com/40802367/177887709-0df27ac2-842a-4f3f-9740-721c1c0d6df1.png)

**Comment by nxwbxdy** [comment]
when I use a new screen (virtual) on my macbook the sidebar is gone because that's like fullscreen. It puts the program on fullscreen and the sidebar is gone and it is not resizable. The thing that remains is the resize bar of the sidebar and nothing else.
<img width="1470" alt="Bildschirm­foto 2023-03-22 um 21 20 06" src="https://user-images.githubusercontent.com/93199725/227028454-6aef2de5-f756-479f-abc7-a8135e4b14d8.png">
The same issue happens if I put a video (example: youtube) in fullscreen mode. The sidebar resize-bar is also visible there
<img width="1470" alt="Bildschirm­foto 2023-03-22 um 21 23 54" src="https://user-images.githubusercontent.com/93199725/227029214-fab2a509-7973-4219-96b3-0c9b02eaa29d.png">
